version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies...."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -9 -r deployment_package.zip lambda_function.py backoff certifi idna marketorestpython-0.5.23-py3.6.egg-info requests-2.27.1.dist-info backoff-1.11.1.dist-info certifi-2024.2.2.dist-info idna-3.6.dist-info pytz charset_normalizer pytz-2024.1.dist-info urllib3 charset_normalizer-2.0.12.dist-info marketorestpython requests urllib3-1.26.18.dist-info
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name email-pref-marketo-dupes --zip-file fileb://deployment_package.zip
      - echo "DONE!!"