version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies...."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -9 -r deployment_package.zip lambda_function.py backoff backoff-2.2.1.dist-info bin certifi certifi-2024.2.2.dist-info charset_normalizer charset_normalizer-3.3.2.dist-info idna idna-3.6.dist-info marketorestpython marketorestpython-0.5.23-py3.11.egg-info pytz pytz-2024.1.dist-info requests requests-2.31.0.dist-info urllib3	urllib3-2.2.1.dist-info
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name email-pref-marketo-dupes --zip-file fileb://deployment_package.zip
      - echo "DONE!"